const styles = {
  main: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: " 100%",
    // margin: "auto",
  },
  mainScreen: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
    width: "100%",
    height: "100%",
    display: "flex",
    marginTop: 30,
  },
  main_display: {
    elevation: 10,
    width: "95%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 10,
    display: "flex",
    // flexDirection: "column",
    // justifyContent: "center",
    marginVertical: 20,
  },
  main_displayText: {
    fontSize: 50,
    textAlign: "right",
  },
  mainScreen_keypad: {
    width: "100%",
    height: "70%",
    display: "flex",
    // flexDirection: "",
  },
  mainScreen_keypadRow: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: 10,
  },
  btn_outer: {
    width: 90,
    height: 90,
    backgroundColor: "white",
    elevation: 10,
    overflow: "hidden",
    borderRadius: 20,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  bg_button: {
    backgroundColor: "white",
    fontSize: 25,
  },
  btn1_outer: {
    width: 90,
    height: 90,
    backgroundColor: "red",
    elevation: 10,
    overflow: "hidden",
    borderRadius: 90,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  bg1_button: {
    // backgroundColor: "white",
    fontSize: 25,
    color: "white",
    fontWeight: "bold",
  },
  btn2_outer: {
    width: 90,
    height: 90,
    backgroundColor: "gray",
    elevation: 10,
    overflow: "hidden",
    borderRadius: 90,
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  bg2_button: {
    backgroundColor: "gray",
    fontSize: 25,
    color: "white",
    fontWeight: "bold",
  },
};

export default styles;
